name: linux-arm

on:
  push:
    branches: [ main ]
    tags: ["*.*.*"]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ runner.os }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          g++ \
          meson \
          ninja-build \
          pkg-config \
          help2man

    - name: Setup Meson
      run: |
        meson setup build \
          --buildtype=release \
          --default-library=shared \
          -Dglib=disabled \
          -Dicu=disabled \
          -Dtests=disabled \
          -Dintrospection=disabled \
          -Ddocs=disabled \
          -Dcairo=disabled \
          -Dgraphite2=disabled \
          -Dgobject=disabled \
          -Dfreetype=disabled \
          -Dcpp_args="-static-libstdc++ -static-libgcc" \
          -Dcpp_link_args="-static-libstdc++ -static-libgcc"

    - name: Build
      run: meson compile -C build

    - name: Distribution
      run: meson dist -C build --no-tests

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: harfbuzz-arm
        path: |
          build/meson-dist/harfbuzz-*.tar.xz
          build/src/libharfbuzz.so*
        if-no-files-found: error
